import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

import { describe, expect, test } from 'bun:test';

import { committedLines, commitTrailerWarnings } from './check-commit-trailers.ts';

const SCRIPT = resolve(import.meta.dir, 'check-commit-trailers.ts');
const GOOD = 'feat: add the thing\n\nBody line.\n\nWorktree: dev-u6-identity\nSession: dev-u6-identity\n';

describe('commitTrailerWarnings', () => {
  test('accepts a message that ends with Worktree then Session', () => {
    expect(commitTrailerWarnings(GOOD)).toEqual([]);
    expect(commitTrailerWarnings('fix: x\n\nWorktree: primary\nSession: my session (c0ffee12)\n')).toEqual([]);
    expect(commitTrailerWarnings('fix: x\n\nWorktree: unknown\nSession: unknown')).toEqual([]);
  });

  test('ignores comment lines and everything below the verbose scissors line', () => {
    const raw = `${GOOD}# Please enter the commit message\n# ------------------------ >8 ------------------------\ndiff --git a/x b/x\n`;
    expect(committedLines(raw).at(-1)).toBe('Session: dev-u6-identity');
    expect(commitTrailerWarnings(raw)).toEqual([]);
  });

  test('warns when the trailers are missing', () => {
    const warnings = commitTrailerWarnings('feat: add the thing\n');
    expect(warnings).toHaveLength(1);
    expect(warnings[0]).toContain('missing forensic trailers');
  });

  test('warns when the trailers are present but not last, or out of order', () => {
    expect(commitTrailerWarnings('feat: x\n\nWorktree: a\nSession: b\nRefs: UPEX-1\n')[0]).toContain('LAST two lines');
    expect(commitTrailerWarnings('feat: x\n\nSession: b\nWorktree: a\n')[0]).toContain('LAST two lines');
  });

  test('warns on a harness-branded session trailer even when the forensic pair is there', () => {
    const raw = 'feat: x\n\nClaude-Session: https://claude.ai/code/session_0123\nWorktree: a\nSession: b\n';
    expect(commitTrailerWarnings(raw)).toEqual(['harness-branded trailer "Claude-Session:" is forbidden; use "Worktree:" + "Session:" instead.']);
    expect(commitTrailerWarnings('feat: x\n\nCodex-Session: 1\nWorktree: a\nSession: b\n')).toHaveLength(1);
  });

  test('warns on AI co-author and generated-with lines, not on human ones', () => {
    expect(commitTrailerWarnings('feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nWorktree: a\nSession: b\n')).toHaveLength(1);
    expect(commitTrailerWarnings('feat: x\n\nGenerated with Claude Code\nWorktree: a\nSession: b\n')).toHaveLength(1);
    expect(commitTrailerWarnings('feat: x\n\nCo-Authored-By: Kai Doe <kai@example.com>\nWorktree: a\nSession: b\n')).toEqual([]);
    // A codegen note is not attribution: "OpenAPI" must not read as "OpenAI".
    expect(commitTrailerWarnings('chore: x\n\nGenerated by the OpenAPI codegen step.\nWorktree: a\nSession: b\n')).toEqual([]);
  });

  test('an empty message has nothing to check', () => {
    expect(commitTrailerWarnings('# only comments\n\n')).toEqual([]);
  });
});

describe('check-commit-trailers CLI', () => {
  test('never blocks: exit 0 with a warning on stderr, and exit 0 on a missing file', () => {
    const dir = mkdtempSync(join(tmpdir(), 'commit trailers '));
    try {
      const file = join(dir, 'COMMIT_EDITMSG');
      writeFileSync(file, 'feat: no trailers\n');
      const warned = Bun.spawnSync({ cmd: [process.execPath, SCRIPT, file], stdout: 'pipe', stderr: 'pipe' });
      expect(warned.exitCode).toBe(0);
      expect(warned.stderr.toString()).toContain('missing forensic trailers');

      writeFileSync(file, GOOD);
      const clean = Bun.spawnSync({ cmd: [process.execPath, SCRIPT, file], stdout: 'pipe', stderr: 'pipe' });
      expect(clean.exitCode).toBe(0);
      expect(clean.stderr.toString()).toBe('');

      const missing = Bun.spawnSync({ cmd: [process.execPath, SCRIPT, join(dir, 'nope')], stdout: 'pipe', stderr: 'pipe' });
      expect(missing.exitCode).toBe(0);
    }
    finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
