import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { contextMapAdvice, contextMapStatuses, isPlaceholderMap } from '../cli/lib/context-maps.ts';
import { parseMap, renderSectionText, resolveMapPath, run } from './context-map.ts';

const FIXTURE = `<!-- generated by project-context mode data; edited in place by business-data-context refresh; do not hand-edit -->
<!doctype html>
<html lang="en">
<head><title>Business data map</title><style>body { color: red; }</style></head>
<body>
<header><h1>Acme</h1></header>
<section id="entity-order" data-sources="src/orders/,db:orders" data-updated="2026-09-30">
  <h2>Order</h2>
  <p>An order is a <code>cart</code> the buyer paid for.</p>
  <figure data-diagram="state" data-for="entity-order">
    <svg viewBox="0 0 400 200"><title id="t">Order states</title><text>PENDING</text><text>PAID</text></svg>
    <figcaption>Order lifecycle</figcaption>
  </figure>
  <table><tr><th>From</th><th>To</th></tr><tr><td>pending</td><td>paid</td></tr></table>
  <ul><li>Soft-deleted: <code>deleted_at</code></li></ul>
</section>
<section id="discovery-gaps" data-sources="" data-updated="2026-09-30">
  <h2>Discovery gaps</h2>
  <p>Refund cron not verified.</p>
</section>
<script>alert(1)</script>
</body></html>`;

const PLACEHOLDER = `<!-- placeholder: run project-context mode data to generate this map -->
<!doctype html><html><head><title>Business data map</title></head><body><section id="placeholder"><h2>Not generated</h2></section></body></html>`;

let repo: string;
let out: string;
let err: string;
const io = { out: (s: string) => { out += s; }, err: (s: string) => { err += s; } };

function writeMap(slug: string, file: string, html: string): void {
  const dir = join(repo, '.agents', 'skills', slug, 'references');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, file), html);
}

beforeEach(() => {
  repo = mkdtempSync(join(tmpdir(), 'context-map-'));
  out = '';
  err = '';
});

afterEach(() => {
  rmSync(repo, { recursive: true, force: true });
});

describe('parseMap', () => {
  test('reads sections with id, date and sources, and drops svg, style and script', () => {
    const map = parseMap(FIXTURE);
    expect(map.title).toBe('Business data map');
    expect(map.placeholder).toBe(false);
    expect(map.sections.map(s => s.id)).toEqual(['entity-order', 'discovery-gaps']);
    const order = map.sections[0];
    expect(order.title).toBe('Order');
    expect(order.updated).toBe('2026-09-30');
    expect(order.sources).toBe('src/orders/,db:orders');
    expect(order.text).toContain('An order is a `cart` the buyer paid for.');
    expect(order.text).toContain('[figure: state - Order lifecycle]');
    expect(order.text).toContain('| From | To |\n| pending | paid |');
    expect(order.text).toContain('- Soft-deleted: `deleted_at`');
    expect(order.text).not.toContain('PENDING');
    expect(order.text).not.toContain('viewBox');
    expect(JSON.stringify(map)).not.toContain('color: red');
    expect(JSON.stringify(map)).not.toContain('alert');
  });

  test('flags a placeholder map by its line-1 banner', () => {
    expect(parseMap(PLACEHOLDER).placeholder).toBe(true);
    expect(isPlaceholderMap(`\n  ${PLACEHOLDER}`)).toBe(true);
    expect(isPlaceholderMap(FIXTURE)).toBe(false);
  });

  test('a section without an id is skipped', () => {
    expect(parseMap('<section><h2>x</h2></section>').sections).toEqual([]);
  });

  test('renderSectionText keeps h3 headings as markdown', () => {
    expect(renderSectionText('<h3>Rules</h3><p>one</p>')).toBe('### Rules\n\none');
  });
});

describe('run', () => {
  test('prints every section of a skill map', () => {
    writeMap('business-data-context', 'business-data-map.html', FIXTURE);
    expect(run(['business-data-context'], repo, io)).toBe(0);
    expect(out).toContain('# Business data map');
    expect(out).toContain('## Order');
    expect(out).toContain('id: entity-order · updated: 2026-09-30');
    expect(out).toContain('## Discovery gaps');
  });

  test('--section prints one section, an unknown id fails naming the known ones', () => {
    writeMap('business-data-context', 'business-data-map.html', FIXTURE);
    expect(run(['business-data-context', '--section', 'discovery-gaps'], repo, io)).toBe(0);
    expect(out).toContain('Refund cron not verified.');
    expect(out).not.toContain('## Order');
    expect(run(['business-data-context', '--section=nope'], repo, io)).toBe(1);
    expect(err).toContain('entity-order, discovery-gaps');
  });

  test('--list prints id, date and sources per line', () => {
    writeMap('business-data-context', 'business-data-map.html', FIXTURE);
    expect(run(['business-data-context', '--list'], repo, io)).toBe(0);
    expect(out.trim().split('\n')[0]).toBe('entity-order\t2026-09-30\tsrc/orders/,db:orders');
  });

  test('a placeholder map exits 0 with a notice naming the generating mode', () => {
    writeMap('business-data-context', 'business-data-map.html', PLACEHOLDER);
    expect(run(['business-data-context'], repo, io)).toBe(0);
    expect(out).toBe('');
    expect(err).toContain('PLACEHOLDER');
    expect(err).toContain('project-context mode data');
  });

  test('an unknown skill fails', () => {
    expect(run(['nope-context'], repo, io)).toBe(1);
    expect(err).toContain('no map found');
  });

  test('a project-local context skill resolves its *-map.html, and a path works too', () => {
    writeMap('billing-context', 'billing-map.html', FIXTURE);
    expect(resolveMapPath('billing-context', repo)).toContain('billing-map.html');
    expect(run(['.agents/skills/billing-context/references/billing-map.html', '--list'], repo, io)).toBe(0);
  });
});

describe('contextMapStatuses', () => {
  test('reports no-skill, placeholder with a legacy map beside it, and generated', () => {
    writeMap('business-data-context', 'business-data-map.html', PLACEHOLDER);
    mkdirSync(join(repo, '.context', 'business'), { recursive: true });
    writeFileSync(join(repo, '.context', 'business', 'business-data-map.md'), '# old');
    writeMap('business-api-context', 'business-api-map.html', FIXTURE);
    const byslug = Object.fromEntries(contextMapStatuses(repo).map(s => [s.skill.slug, s]));
    expect(byslug['business-data-context'].state).toBe('placeholder');
    expect(byslug['business-data-context'].legacyPresent).toEqual(['.context/business/business-data-map.md']);
    expect(byslug['business-api-context'].state).toBe('generated');
    expect(byslug['business-e2e-context'].state).toBe('no-skill');
    expect(contextMapAdvice(byslug['business-data-context'])).toContain('is kept and will be read as input');
    expect(contextMapAdvice(byslug['business-api-context'])).toBeNull();
    expect(contextMapAdvice(byslug['business-e2e-context'])).toBeNull();
  });

  test('a discovery-generated map names its discovery phase and every old file kept beside it', () => {
    mkdirSync(join(repo, '.agents', 'skills', 'infra-context', 'references'), { recursive: true });
    mkdirSync(join(repo, '.context', 'SRS'), { recursive: true });
    mkdirSync(join(repo, '.context', 'infrastructure'), { recursive: true });
    writeFileSync(join(repo, '.context', 'SRS', 'architecture.md'), '# old');
    writeFileSync(join(repo, '.context', 'infrastructure', 'backend.md'), '# old');
    const infra = contextMapStatuses(repo).find(s => s.skill.slug === 'infra-context')!;
    expect(infra.state).toBe('no-map');
    expect(infra.legacyPresent).toEqual(['.context/SRS/architecture.md', '.context/infrastructure/backend.md']);
    const advice = contextMapAdvice(infra)!;
    expect(advice).toContain('are kept and will be read as input');
    expect(advice).toContain('project-discovery Phases 2-3');
  });

  test('a generated map never reports its old files', () => {
    writeMap('business-domain-context', 'business-domain-map.html', FIXTURE);
    mkdirSync(join(repo, '.context', 'business'), { recursive: true });
    writeFileSync(join(repo, '.context', 'business', 'domain-glossary.md'), '# old');
    const domain = contextMapStatuses(repo).find(s => s.skill.slug === 'business-domain-context')!;
    expect(domain.state).toBe('generated');
    expect(domain.legacyPresent).toEqual([]);
    expect(contextMapAdvice(domain)).toBeNull();
  });
});
