/**
 * @fileoverview The context maps: one HTML file per shipped context skill, the
 * single source of a synthesis a human browses and an AI reads through
 * `bun run context:map` (scripts/context-map.ts).
 *
 * Principle (`agentic-qa-core/references/skill-scaffold.md` §3): `.context/`
 * holds what a SCRIPT pulls from a source of truth; what an AI SYNTHESIZES
 * lives in a skill. The business maps, the domain map and the infra map are
 * synthesis, so each one lives inside its own context skill at
 * `references/<map>.html`, generated by `project-context` or
 * `project-discovery` and edited section by section afterwards.
 *
 * This module is the ONE list of those skills, shared by the reader, the
 * updater (bootstrap delivery + informational parity rows) and the doctor.
 * Import-closed: node builtins only (AGENTS.md §4.5), so `scripts/` imports it,
 * never the other way round.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

export interface ContextMapSkill {
  /** Skill slug under `.agents/skills/`. */
  slug: string
  /** File name of the map inside the skill's `references/`. */
  map: string
  /** The skill step that generates the map, as a user runs it (`project-context mode data`). */
  generator: string
  /**
   * The markdown files this map replaces, kept in a consumer repo and read as
   * generator input. Never deleted by anything upstream ships.
   */
  legacy: readonly string[]
}

/**
 * Context skills upstream ships as placeholders. Unlike every other
 * `<aspect>-context` (project-local by construction, `isProjectLocalSkillPath`),
 * the updater DELIVERS each of these once when its folder is absent, then never
 * overwrites or deletes it: the map inside is the project's own synthesis.
 */
export const CONTEXT_MAP_SKILLS: readonly ContextMapSkill[] = [
  { slug: 'business-data-context', map: 'business-data-map.html', generator: 'project-context mode data', legacy: ['.context/business/business-data-map.md'] },
  { slug: 'business-api-context', map: 'business-api-map.html', generator: 'project-context mode api', legacy: ['.context/business/business-api-map.md'] },
  {
    slug: 'business-e2e-context',
    map: 'business-e2e-map.html',
    generator: 'project-context mode e2e',
    legacy: ['.context/business/business-feature-map.md', '.context/PRD/user-personas.md', '.context/PRD/user-journeys.md', '.context/SRS/functional-specs.md'],
  },
  {
    slug: 'business-domain-context',
    map: 'business-domain-map.html',
    generator: 'project-discovery Phase 1',
    legacy: ['.context/business/business-model.md', '.context/business/domain-glossary.md'],
  },
  {
    slug: 'infra-context',
    map: 'infra-map.html',
    generator: 'project-discovery Phases 2-3',
    legacy: [
      '.context/SRS/architecture.md',
      '.context/SRS/non-functional-specs.md',
      '.context/infrastructure/backend.md',
      '.context/infrastructure/frontend.md',
      '.context/infrastructure/infrastructure.md',
    ],
  },
];

export const CONTEXT_MAP_SLUGS: ReadonlySet<string> = new Set(CONTEXT_MAP_SKILLS.map(s => s.slug));

/** Line 1 of a map that has not been generated yet. */
export const PLACEHOLDER_BANNER_PREFIX = '<!-- placeholder:';
/** Line 1 of a generated map (`<!-- generated by <generator>; ... -->`). */
export const GENERATED_BANNER_PREFIX = '<!-- generated by ';

export function contextMapSkill(slug: string): ContextMapSkill | undefined {
  return CONTEXT_MAP_SKILLS.find(s => s.slug === slug);
}

/** Repo-relative path of a skill's map, forward slashes. */
export function mapRelPath(skill: ContextMapSkill, skillsDir = '.agents/skills'): string {
  return `${skillsDir.replace(/\\/g, '/').replace(/\/+$/, '')}/${skill.slug}/references/${skill.map}`;
}

/** True when the HTML is a placeholder map (banner on its first non-empty line). */
export function isPlaceholderMap(html: string): boolean {
  const first = html.replace(/^\uFEFF/, '').trimStart().split(/\r?\n/, 1)[0] ?? '';
  return first.startsWith(PLACEHOLDER_BANNER_PREFIX);
}

export type MapState = 'no-skill' | 'no-map' | 'placeholder' | 'generated';

export interface MapStatus {
  skill: ContextMapSkill
  state: MapState
  /** The legacy markdown files that exist beside a missing or placeholder HTML map. */
  legacyPresent: readonly string[]
}

/** State of every shipped context map in a repo. Read-only. */
export function contextMapStatuses(repoRoot: string): MapStatus[] {
  return CONTEXT_MAP_SKILLS.map((skill) => {
    const skillDir = join(repoRoot, '.agents', 'skills', skill.slug);
    const mapPath = join(skillDir, 'references', skill.map);
    let state: MapState;
    if (!existsSync(skillDir)) { state = 'no-skill'; }
    else if (!existsSync(mapPath)) { state = 'no-map'; }
    else { state = isPlaceholderMap(readFileSync(mapPath, 'utf8')) ? 'placeholder' : 'generated'; }
    const legacyPresent = state === 'generated'
      ? []
      : skill.legacy.filter(rel => existsSync(join(repoRoot, ...rel.split('/'))));
    return { skill, state, legacyPresent };
  });
}

/** One human line per map that still needs generating; empty when every map is generated. */
export function contextMapAdvice(status: MapStatus): string | null {
  if (status.state === 'generated' || status.state === 'no-skill') { return null; }
  const what = status.state === 'no-map' ? 'has no map' : 'holds a placeholder map';
  const old = status.legacyPresent.map(rel => `\`${rel}\``).join(', ');
  const legacy = status.legacyPresent.length === 0
    ? ''
    : `; your old ${old} ${status.legacyPresent.length === 1 ? 'is' : 'are'} kept and will be read as input`;
  return `\`${status.skill.slug}\` ${what}${legacy}: run \`${status.skill.generator}\``;
}
